# Generated by Django 2.1.1 on 2018-11-16 16:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_text', models.TextField()),
                ('simp_text', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('img', models.ImageField(default='img/picture.jpg', upload_to='img')),
                ('realname', models.CharField(default='', max_length=20)),
                ('sex', models.CharField(default='', max_length=2)),
                ('birthday', models.DateField(default=datetime.date(1970, 1, 1))),
                ('telephone', models.CharField(default='', max_length=11)),
            ],
        ),
        migrations.AddField(
            model_name='diary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary_main.User'),
        ),
    ]
