# Generated by Django 2.1.1 on 2018-11-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_main', '0003_auto_20181117_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diary',
            name='simp_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='diary',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
