# Generated by Django 2.1.1 on 2018-11-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_main', '0004_auto_20181125_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.FileField(default='/media/images/picture.jpg', upload_to='media/images'),
        ),
    ]
