# Generated by Django 2.1.1 on 2018-11-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_main', '0005_auto_20181125_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.FileField(default='/media/images/picture.jpg', upload_to='images'),
        ),
    ]
