# Generated by Django 2.1.1 on 2018-12-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_main', '0006_auto_20181125_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='praise',
            field=models.IntegerField(default=0),
        ),
    ]
